__use_yte__: true
# this config needs to be parsed with YTE
# input configuration
server: mcclintock
#
metadata: config/metadata.csv
targetfile: config/targets.txt
#
## status notification email address. Comma separated is OK.
#
email: mgaley@uw.edu
#
output_dir: results
#
# QDNAseq options
cnv_binsize: 50
?if this["server"] == "mcclintock":
  geneAnnotationBed: /n/dat/hg38/resorted.hg38.genes.mergedintervals.bed
?else:
  geneAnnotationBed: /data/dat/hg38/resorted.hg38.genes.mergedintervals.bed

# resources
threads: 40
#
# conda environment names
# these environments are expected to already exist.
conda_samtools: samtools-1.19
conda_bedtools: bedtools-2.31.1
conda_qdnaseq: qdnaseq-1.40.0
#
# sample identifier pattern # this line probably wont work
sampleidpattern: r"M\d\d\d\d"